model: "allenai/OLMo-2-0425-1B"
revision: "stage1-step100000-tokens210B"
artifact_path: "../artifacts/allenai/OLMo-2-0425-1B/Training_Analysis/100000"
results_path: "../results/allenai/OLMo-2-0425-1B/Training_Analysis/100000"
dtype: "bfloat16"
only_linear: true