model: "allenai/OLMo-2-0425-1B"
revision: "stage1-step1000000-tokens2098B"
artifact_path: "../artifacts/allenai/OLMo-2-0425-1B/Training_Analysis/1000000"
results_path: "../results/allenai/OLMo-2-0425-1B/Training_Analysis/1000000"
dtype: "bfloat16"
only_linear: true