model: "allenai/OLMo-2-0425-1B"
revision: "stage1-step500000-tokens1049B"
artifact_path: "../artifacts/allenai/OLMo-2-0425-1B/Training_Analysis/500000"
results_path: "../results/allenai/OLMo-2-0425-1B/Training_Analysis/500000"
dtype: "bfloat16"
only_linear: true