model: "openai-community/gpt2-medium"
artifact_path: "../artifacts/openai-community/gpt2-medium/Linear_Representation"
results_path: "../results/openai-community/gpt2-medium/Linear_Representation"
dtype: "bfloat16"