model: "openai-community/gpt2-large"
dataset_path: "goulding/adults.csv"
results_path: "../results/openai-community/gpt2-large/Calibration"
representation_type: "Linear_Representation"
dtype: "bfloat16"