model: "allenai/OLMo-2-1124-7B"
revision: "stage1-step150-tokens1B"
artifact_path: "../artifacts/allenai/OLMo-2-1124-7B/Training_Analysis/150"
results_path: "../results/allenai/OLMo-2-1124-7B/Training_Analysis/150"
dtype: "bfloat16"
only_linear: true