model: "allenai/OLMo-2-1124-7B"
revision: "stage1-step25000-tokens105B"
artifact_path: "../artifacts/allenai/OLMo-2-1124-7B/Training_Analysis/25000"
results_path: "../results/allenai/OLMo-2-1124-7B/Training_Analysis/25000"
dtype: "bfloat16"
only_linear: true