model: "allenai/OLMo-2-1124-7B"
revision: "stage1-step928000-tokens3893B"
artifact_path: "../artifacts/allenai/OLMo-2-1124-7B/Training_Analysis/928000"
results_path: "../results/allenai/OLMo-2-1124-7B/Training_Analysis/928000"
dtype: "bfloat16"
only_linear: true